---
# vars file for osp.servers
osp_servers:
  frontend:
    name: frontend
    state: present
    image: rhel-server-7.7-update-2
    key_name: gitopsuserkey
    flavor: m1.small
    security_group: gitops01-DefaultSG
    meta:
      - { group: frontends, deployment_name: QA}
  app1:
    name: app1
    state: present
    image: rhel-server-7.7-update-2
    key_name: ansible_ssh
    flavor: m1.small
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  app2:
    name: app2
    state: present
    image: rhel-server-7.7-update-2
    key_name: gitopsuserkey
    flavor: m1.small
    security_group: gitops01-DefaultSG
    meta:
      - { group: apps, deployment_name: QA}
  db:
    name: db
    state: present
    image: rhel-server-7.7-update-2
    key_name: gitopsuserkey
    flavor: m1.small
    security_group: gitops01-DefaultSG
    meta:
      - { group: appdbs, deployment_name: QA}
